### PR TITLE
android: Update Xbox 360 Controller configs

### PR DESCRIPTION
**Pull request by landfillbaby**

### CODE REVIEW

**Comment by landfillbaby** [comment]
i just noticed something. in the config for the wired version:

```
input_b_btn_label = "A"
input_y_btn_label = "X"
[...]
input_a_btn_label = "B"
input_x_btn_label = "Y"
```

but in the wireless adapter version, they're not swapped like that.

this is obviously due to nintendo/xbox differences. but which one is right?

**Comment by hizzlekizzle** [comment]
I would assume the swapped version is correct from a physical layout standpoint, which is typically how we handle things.

**Comment by landfillbaby** [comment]
ready for merge :)

**Comment by landfillbaby** [comment]
oh just realised this could be merged using https://github.com/libretro/RetroArch/pull/16990

**Comment by landfillbaby** [comment]
```md
this is the proper footnote[^1] syntax.

[^1]: or reference.
```

**Comment by RobLoach** [comment]
Since we're making updates here, I think it would be appropriate to do the merge. Also, if you're curious about the button layout for A/B, you'll find it here...
https://www.lakka.tv/doc/Input-settings/

The A button is on the far right. B is the one at the bottom.

**Comment by landfillbaby** [comment]
done :)

**Comment by RobLoach** [comment]
Have you been able to test this on your Android device? Would like to make sure it's working before we merge it.

**Comment by landfillbaby** [comment]
yes i tested and it's fine

**Pull request merged**
