### PR TITLE
Create android/DualSense Wireless Controller (Android 12).cfg

### PR DESCRIPTION
**Pull request by davidhedlund**
# Blocker (solved)
To make it possible to modify or rename autoconfig files in Android, which is requires for multiple cfg files for the same controller, this should be solved first: [Change the default value of "Settings -> Directory -> Controller Profiles" to "/storage/emulated/0/RetroArch/autoconfig"](https://github.com/libretro/RetroArch/issues/15996)

It would be great if you could comment on that issue.

# Info
Generated from
* OS: Google TV 12 (it's based on Android 12, see below). Kernel version: 5.4 (Google TV: Settings -> System -> About -> Kernel version)
* RA installed via: Google Play
* Retroarch version: 1.9.12

RetroArch:
* Main Menu -> Information -> System Information -> Frontend Identifier: android [default]
* Main Menu -> Information -> System Information -> Frontend Name: Chromecast HD
* Main Menu -> Information -> System Information -> Frontend OS: Android (v12.0)
* Settings -> Drivers -> Controller -> Controller: android [default]

android/Dual Sense 5.cfg didn't work in Google TV 10. For more info see:
* https://github.com/libretro/retroarch-joypad-autoconfig/issues/940

### CODE REVIEW

**Comment by davidhedlund** [comment]
There's no way to rename the .cfg files in Android for most people, since their phones are not rooted, right?

* More people need to verify that my PR is working in Android 12.
* Then we need to decide if we should rename the current android/Sony_DualSense.cfg to android/Sony_DualSense_(old).cfg, and Sony_DualSense_(Android_12).cfg to Sony_DualSense.cfg -- to make it consistent with udev/[Nintendo - Switch Pro Controller (old).cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Nintendo%20-%20Switch%20Pro%20Controller%20(old).cfg) and [Nintendo - Switch Pro Controller.cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Nintendo%20-%20Switch%20Pro%20Controller.cfg)

**Comment by davidhedlund** [comment]
> Hi, how is this PR going? Can it be merged or does something remain to be done?

I need to re-evaluate the autoconfig once and for all before we can merge it. It will take no more than 1-2 weeks since I need to reinstall Android on a test device.

**Comment by davidhedlund** [comment]
@RobLoach Why did you close this one, and?:
* https://github.com/libretro/retroarch-joypad-autoconfig/pull/1088#event-11606091414

**Comment by RobLoach** [comment]
Feel free to make a new one when you're ready. Drafts that stay dormant are a distraction.

**Comment by davidhedlund** [comment]
> Feel free to make a new one when you're ready. Drafts that stay dormant are a distraction.

I understand.

Can I create a single PR for multiple file edits? For example, a PR that:
* A new autoconfig that adds Sony DualSense (Android 13)
* An edited file totally unrelated to Sony DualSense. For example, correct the `input_device` variable in an existing file for a Nintendo autoconfig file.

**Review by davidhedlund — COMMENTED** [review]
ready

**Comment by davidhedlund** [comment]
> Feel free to make a new one when you're ready. Drafts that stay dormant are a distraction.

It's so ready

**Comment by davidhedlund** [comment]
But should we change the file name from "DualSense Wireless Controller (Android 12).cfg" to "DualSense Wireless Controller (Chromecast HD).cfg" ?

It's a hazzle to know precisely which android versions that are compatible. Somtime an autoconfig may:
* work with android 11
*not with android 12
* Workd with android 13

This autoconfig is maintained to work for Chromecast HD

**Pull request closed without merging**
