### PR TITLE
Add support for AxisPad Colors

### PR DESCRIPTION
**Pull request by Kurlon**
Tested on Generic.x86_64-2.2.2, only tested via USB as I don't have any systems with classic game ports any more.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
This looks good so far. Can I trouble you to add the button labels while you're at it?

**Comment by Kurlon** [comment]
Didn't realize those were a thing, I see the format in some of the other confs and will correct.

**Comment by twinaphex** [comment]
Hi there, any update here?

**Comment by twinaphex** [comment]
I found some screenshots of the pad here -
https://www.ebay.com/itm/Axis-Pad-Colors-Interact-Controller-for-Pc-Complete-Teal-Clear-8-Button-2036-/264284954646
Based on this, we could add the labels ourselves.

**Comment by Kurlon** [comment]
I'm horribly sorry, I completely spaced on this.  I'll do it tonight.

**Comment by twinaphex** [comment]
Thanks.

**Comment by Kurlon** [comment]
Let me know if I gaffed at all.

**Pull request merged**
