### PR TITLE
Add support for WeTek Gamepad

### PR DESCRIPTION
**Pull request by codesnake**
Add support for WeTek Gamepad gaming controller.

See https://wetek.com/ww/en/product/gamepad for more details.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
That looks good so far, but would you mind adding the button labels, as well? That will make it easier to remap them in the 'controls' menu.

**Comment by codesnake** [comment]
@hizzlekizzle Sure, I will add the labels.

**Comment by codesnake** [comment]
Button labels added.

**Comment by hizzlekizzle** [comment]
Perfect! Thanks!

**Pull request merged**
