### PR TITLE
Vendor and product id messed up, interfering with other gamepads

### PR DESCRIPTION
**Pull request by rdlu**
I think these vendor and product ids are not quite right.

Just got an fake PS3 and a original one and both didn't worked until removing these two lines.

 Now the three controllers (PS3 and ipega) are working.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Hmm. Without those lines, the pads are only matching by name, which is pretty risky to rely on.

**Comment by paalfe** [comment]
Is the vendor id and product id in HEX or Decimal format?

```
# Hex vid:pid is found using "dmesg -w" or "tail -f /var/log/syslog" and converted to Decimal using http://www.binaryhexconverter.com/hex-to-decimal-converter
# Hex vid:pid = 0f0d:0085 -> Decimal vid:pid = 3853:133
```

Also, the file should be renamed to "iPEGA_PG_9021_BT.cfg".

**Comment by rdlu** [comment]
The first thing I noticed is that putting the display name (I configured correctly the first time), all my three gamepads are "identified" as ipega in retroarch initialization messages.

My dmesg -w, after connecting only ipega:

`[   71.152500] input: ipega classic gamepad as /devices/pci0000:00/0000:00:13.0/usb8/8-3/8-3:1.0/bluetooth/hci0/hci0:256/0005:1949:0402.0005/input/input24
[   71.153182] hid-generic 0005:1949:0402.0005: input,hidraw4: BLUETOOTH HID v1.1b Keyboard [ipega classic gamepad] on ac:7b:a1:9c:00:53
`

Archlinux doesn't have syslog, replaced by journalctl, that has exactly same message from dmesg.

udevadm info -an /dev/input/js0:
`  looking at device '/devices/pci0000:00/0000:00:13.0/usb8/8-3/8-3:1.0/bluetooth/hci0/hci0:256/0005:1949:0402.0005/input/input24/js0':
    KERNEL=="js0"
    SUBSYSTEM=="input"
    DRIVER==""

  looking at parent device '/devices/pci0000:00/0000:00:13.0/usb8/8-3/8-3:1.0/bluetooth/hci0/hci0:256/0005:1949:0402.0005/input/input24':
    KERNELS=="input24"
    SUBSYSTEMS=="input"
    DRIVERS==""
    ATTRS{name}=="ipega classic gamepad"
    ATTRS{phys}=="ac:7b:a1:9c:00:53"
    ATTRS{properties}=="0"
    ATTRS{uniq}=="58:ea:4f:41:e8:57"

.... lot more about my Intel Bluetooth Controller
`

As I recall all other ipega models have a completely different names, so I thought to be "safe".

Connecting the ipega and the Dual Shock 3 at same time (DS3 as player 2)

`[  754.690931] input: ipega classic gamepad as /devices/pci0000:00/0000:00:13.0/usb8/8-3/8-3:1.0/bluetooth/hci0/hci0:256/0005:1949:0402.0006/input/input25
[  754.691504] hid-generic 0005:1949:0402.0006: input,hidraw4: BLUETOOTH HID v1.1b Keyboard [ipega classic gamepad] on ac:7b:a1:9c:00:53
[  759.761116] input: PLAYSTATION(R)3 Controller as /devices/pci0000:00/0000:00:13.0/usb8/8-3/8-3:1.0/bluetooth/hci0/hci0:512/0005:054C:0268.0007/input/input26
[  759.761324] sony 0005:054C:0268.0007: input,hidraw5: BLUETOOTH HID v1.00 Joystick [PLAYSTATION(R)3 Controller] on ac:7b:a1:9c:00:53
`

**Comment by rdlu** [comment]
Related? https://github.com/libretro/RetroArch/issues/2961

**Comment by rdlu** [comment]
Since The Playstation 3 profiles matched the hwinfo, I used the same for ipega. First time I just used the save autoconfig option inside retroarch and made adjustments.

It works same as having nothing (just fine).

But as per @Kivutar comment at https://github.com/libretro/RetroArch/issues/2961, I dont think it is relevant.

Will upload in a minute.

**Comment by rdlu** [comment]
Just uploaded.

Thanks guys for helping me :+1:

**Pull request merged**
