### PR TITLE
Add autoconfig for ipega PG-9087 controller

### PR DESCRIPTION
**Pull request by fasheng**
ipega PG-9087 could connect to PC/Android with bluetooth or wired USB, for bluetooth, its device name is "PG-9087", and for USB it just actor as "ShanWan     PC/PS3/Android Gamepad".

http://ipega.hk/gamehandle/53-97.html

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
These look good, thanks! Is there a reason some of them don't have the button labels?

**Comment by fasheng** [comment]
Yes, just not sure the label names for ShanWan before, now I copy them from `udev/SHANWAN PS3 GamePad.cfg` and update PG-8097's labels, too.

Please review again.

**Comment by DartPower** [comment]
My iPega PG-9087s detecting as Ipega 9023

**Comment by fasheng** [comment]
Well, main is PG-9087 not PG-9087s, and both work OK for Linux and Android.

Here is the official page for 9087s, so they are two different modes in fact:
http://ipega.hk/gamehandle/53-194.html

I guess there buttons should be similar, so you could edit the `input_product_id` in config file and test in local. Good luck!

**Pull request merged**
