### PR TITLE
Create Gasia_Co.,Ltd_PS(R)_Gamepad.cfg

### PR DESCRIPTION
**Pull request by duduke**
Autoconfig for NYKO Raven Wireless PS3 controller.
The controller acts like a wired PS3 controller but has a wireless 2.4ghz dongle.
This is how the controller looks like: http://www.ign.com/articles/2010/12/22/nyko-raven-review

### CODE REVIEW

**Comment by Kivutar** [comment]
Hi! Nice contribution, thank you. Any vid:pid for the controller or the dongle?

**Comment by duduke** [comment]
Sure. But don't really know how to. 
Can you guide me?
(I have a mac)

**Comment by Kivutar** [comment]
On mac there is a command called system_profiler I think.

**Comment by duduke** [comment]
This is what I could gather from lsusb and dmesg:
lslusb:
Bus 001 Device 007: ID 054c:0268 Sony Corp. Batoh Device / PlayStation 3 Controller

dmesg:
[218752.683021] usb 1-1.4: new full-speed USB device number 7 using dwc_otg
[218752.783129] usb 1-1.4: New USB device found, idVendor=054c, idProduct=0268
[218752.783161] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[218752.783176] usb 1-1.4: Product: PS(R) Gamepad
[218752.783190] usb 1-1.4: Manufacturer: Gasia Co.,Ltd
[218762.789738] sony 0003:054C:0268.0003: usb_submit_urb(ctrl) failed: -1
[218762.789776] sony 0003:054C:0268.0003: timeout initializing reports
[218762.790377] input: Gasia Co.,Ltd PS(R) Gamepad as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/0003:054C:0268.0003/input/input4
[218762.793939] sony 0003:054C:0268.0003: input,hiddev0,hidraw0: USB HID v1.11 Joystick [Gasia Co.,Ltd PS(R) Gamepad] on usb-3f980000.usb-1.4/input0

**Comment by duduke** [comment]
I've added the vid:pid to the config file.

**Pull request merged**
