### PR TITLE
Samsung Game Pad EI-GP20 config

### PR DESCRIPTION
**Pull request by p0ngbr**
Config files for udev and xinput

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Looks good! While we have you, would you mind adding the button labels, as well? It makes it easier for people to remap them.

Here's an example of what they look like:
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Sony-PlayStation3-DualShock3-Controller-Bluetooth.cfg

**Comment by p0ngbr** [comment]
Sure! I'll make these changes now.

2016-07-14 9:50 GMT-03:00 hizzlekizzle <notifications@github.com>:

> Looks good! While we have you, would you mind adding the button labels, as
> well? It makes it easier for people to remap them.
>
> Here's an example of what they look like:
>
> https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Sony-PlayStation3-DualShock3-Controller-Bluetooth.cfg
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/libretro/retroarch-joypad-autoconfig/pull/212#issuecomment-232656255>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADsDMheOxaNCiwTUTaoepvSl9mCUp8Hsks5qVjCngaJpZM4JMDfQ>
> .
>



-- 
*Renato Santos*
about.me/p0ng

**Comment by p0ngbr** [comment]
Done :)

**Comment by hizzlekizzle** [comment]
Ah, beautiful :)

Thanks!

**Pull request merged**
