### PR TITLE
Add DIGIGEAR JOYPAD USB 2.0

### PR DESCRIPTION
**Pull request by candrapersada**

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Can I trouble you to add the button labels while you're at it?

**Comment by candrapersada** [comment]
image

**Comment by candrapersada** [comment]
why update retroarch-joypad-autoconfig to flathub slow?

**Comment by RobLoach** [comment]
> why update retroarch-joypad-autoconfig to flathub slow?

It's done manually... You have two options:

1. Submit a Pull Request to update the commit hash
2. Wait for a RetroArch tag and a Flatpak update

**Comment by candrapersada** [comment]
how to Pull Request to update the commit hash for update DragonRise Inc. Generic USB Joystick.cfg to Flatpak?

**Pull request closed without merging**
