### PR TITLE
Add xinput autoconfigs for 8bitdo N64 Gamepad

### PR DESCRIPTION
**Pull request by tony971**
This currently has a conflict with the FC30 Pro controller, as both have the same vendor and product IDs while in bluetooth mode.

### CODE REVIEW

**Comment by paalfe** [comment]
I'll update the other xinput 8Bitdo configs (8Bitdo Pro gamepad firmware v1.71 (2016-09-06) requires updated configs, at least for the Bluetooth configs) and see how this can be resolved.

**Comment by paalfe** [comment]
Do you have firmware v1.10?
http://download.8bitdo.com/Firmware/n64/

**Comment by tony971** [comment]
I had 1.0 but 1.10 still uses the same info.

**Comment by paalfe** [comment]
This pull can be deleted, I have included 8Bitdo N64 USB and BT configs in my pull #251. "8Bitdo_N64_BT_(disabled).cfg" with disabled VID:PID so it won't conflict with "8Bitdo_Pro_FC30_BT.cfg". The user has to manually enable VID:PID in "8Bitdo_N64_BT_(disabled).cfg" and disable in "8Bitdo_Pro_FC30_BT.cfg" for "8Bitdo_N64_BT_(disabled).cfg" to automatically work.

**Comment by tony971** [comment]
Wait, I lied. With the firmware update, the bluetooth vendor ID changes to 14384. With that change, there is no conflict. I'm terrible with github so if you wanted to make this change, I'll delete this pull.

**Comment by paalfe** [comment]
Perfect 👍. I have update pull #251 with the new VID.

**Pull request closed without merging**
