### PR TITLE
docs: Clean up some documenation

### PR DESCRIPTION
**Pull request by offalynne**
Attribution occurs through project documentation and commit history, not contributor graffiti

### CODE REVIEW

**Comment by davidhedlund** [comment]
> Attribution occurs through project documentation and commit history, not contributor graffiti

Please restore "# Requires Android 12 or later." and try to use a more friendlier tone next time.

**Comment by offalynne** [comment]
The comment regarding OS version is unnecessary and irrelevant to the purpose of the project

#1140, #1148, #1149, #1150, #1153, #1156, #1158, #1159, #1160, #1161, #1164, #1168, #1166, #1167, #1171, #1172, #1174, #1175, #1176, #1177 should similarly be amended or closed outright for an excess of redundant and/or outright mistaken commentary and minimal content

**Comment by davidhedlund** [comment]
> The comment regarding OS version is unnecessary and irrelevant to the purpose of the project
> 
> #1140, #1148, #1149, #1150, #1153, #1156, #1158, #1159, #1160, #1161, #1164, #1168, #1166, #1167, #1171, #1172, #1174, #1175, #1176, #1177 should similarly be amended or closed outright for an excess of redundant and/or outright mistaken commentary and minimal content

I've gone ahead and removed all the comments from the pull requests, including the one at [this link](https://github.com/libretro/retroarch-joypad-autoconfig/pull/1158/commits/1744f7af930d222fc600b5ac3c56f5d10720954c). Please feel free to close this PR at your convenience.

**Comment by davidhedlund** [comment]
By the way, I refrained from appending my name to other files or pull requests. The extensive commenting was due to manually altering variables from the generated autoconfig files to grasp how to construct them from source using a script. 

I possess the following controllers:
*  Sony DualSense
* Sony DualShock 4 v2
* Nintendo Switch Pro Controller

I'm planning to purchase a Microsoft Series S/X Wireless controller by month's end. These controllers are available in retail and serve as the official controllers for contemporary gaming consoles. My objective is to ensure their compatibility with RetroArch.

However, I concur that this repository isn't the appropriate venue for such comments. Instead, a separate release database could be established for the controller I'm aiming to maintain.

You might not fully appreciate the time investment required to reach this point—approximately 60-80 working hours to master the generation, modification, and documentation of these autoconfig files, as well as submitting the following:
* [libretro/docs joypad user guide](https://github.com/libretro/docs/pulls?q=is%3Apr+author%3Adavidhedlund+is%3Aclosed+)
* [RetroArch Issues](https://github.com/libretro/RetroArch/issues/created_by/davidhedlund)]https://github.com/libretro/RetroArch/issues/created_by/davidhedlund
* [Meta-Issue: Cross-platform controller configuration and autoconfig file generation issues](https://github.com/libretro/retroarch-joypad-autoconfig/issues/1143)

**Comment by davidhedlund** [comment]
> The comment regarding OS version is unnecessary and irrelevant to the purpose of the project
> 
> #1140, #1148, #1149, #1150, #1153, #1156, #1158, #1159, #1160, #1161, #1164, #1168, #1166, #1167, #1171, #1172, #1174, #1175, #1176, #1177 should similarly be amended or closed outright for an excess of redundant and/or outright mistaken commentary and minimal content

I understand your concerns about the comments, and I appreciate your feedback. I've taken the initiative to remove all comments from the pull requests, ensuring that every file is now completely free of comments. This includes the [file](https://github.com/libretro/retroarch-joypad-autoconfig/pull/1158/commits/1744f7af930d222fc600b5ac3c56f5d10720954c) associated with this PR. Please feel free to close this PR at your convenience.

I want to clarify that I didn't append my name to other files or pull requests. The extensive commenting was part of my efforts to manually alter variables from the generated autoconfig files as I learned how to program a script to automate the process.

Regarding my work with controllers, I currently own the following:
* Sony DualSense
* Sony DualShock 4 v2
* Nintendo Switch Pro Controller

I'm planning to purchase a Microsoft Series S/X Wireless controller by month's end. These controllers are available in retail and serve as the official controllers for contemporary gaming consoles. My objective is to ensure their compatibility with RetroArch.

I'm also planning to purchase a Microsoft Series S/X Wireless controller by the end of the month. These controllers are widely available and are the official controllers for modern gaming consoles. My goal is to ensure their compatibility with RetroArch.

I agree that this repository isn't the right place for these comments. Instead, creating a dedicated release JSON for the controllers I'm working to maintain would be more appropriate.

I understand it might not be immediately apparent, but reaching this point has required a significant investment of both time and resources. Since May of last year, I've been focused on mastering the generation, modification, and documentation of these autoconfig files. I've also developed configuration scripts for all RetroArch packages, including Flatpak, AppImage, and GNU/Linux packages. This includes dedicating around two months to these efforts, as well as submitting the following:
* [libretro/docs joypad user guide](https://github.com/libretro/docs/pulls?q=is%3Apr+author%3Adavidhedlund+is%3Aclosed+)
* [RetroArch Issues](https://github.com/libretro/RetroArch/issues/created_by/davidhedlund)
* [Meta-Issue: Cross-platform controller configuration and autoconfig file generation issues](https://github.com/libretro/retroarch-joypad-autoconfig/issues/1143)

I hope you can understand and support me as I continue to work on these improvements.

**Comment by davidhedlund** [comment]
I just added a [commit](https://github.com/libretro/docs/pull/974/commits/09269e1e27b563559e91020a425e6316da9cc007) with edit summary: "Text was removed to incorporate comments into the autoconfig files following consensus: https://github.com/libretro/retroarch-joypad-autoconfig/pull/1181#issuecomment-2307819888. This user guide is sufficiently documented to serve as a reference instead of including comments within the files."

**Comment by offalynne** [comment]
I think we have different ideas regarding what "improvement" means in the context of these changes

**Comment by davidhedlund** [comment]
> I think we have different ideas regarding what "improvement" means in the context of these changes

Are my pull requests satisfactory, or is there anything else you'd like me to address?

**Review by RobLoach — APPROVED** [review]
I tend to agree here. Much of this is cruft and not needed...

- Attribution is available through git history, and content is licensed as MIT
- While backwards compatibility is important, in general we usually try to target the latest drivers/versions of platforms
- It's known that there are other binding files, as you can see the other binding files in the same directory

**Pull request merged**
