### PR TITLE
Add Retro-bit Saturn Bluetooth controller autoconfigs (Dinput and Xin…

### PR DESCRIPTION
**Pull request by spec-chum**
…put pad modes) for Retroarch Xinput

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
the dinput mode one looks good, but it seems the xinput one is just using generic vid and pid, so we can't add it without breaking a lot of other controllers. Would you mind removing it from the PR so I can merge just the dinput one?

**Comment by spec-chum** [comment]
Ah, bloody retro-bit, I should have known,big clue was the device name, in hindsight! 

Didn't realise, sorry. 

Will sort today.

**Comment by offalynne** [comment]
at least the DInput mode's VID/PID are salvagble for this one :cry: :pray:

**Comment by spec-chum** [comment]
Removed :)

**Comment by hizzlekizzle** [comment]
Beautiful, thanks!

**Pull request merged**
