### PR TITLE
Added Thrustmaster T-Flight Joystick

### PR DESCRIPTION
**Pull request by Jaffacakelover**
Added Thrustmaster T-Flight Hotas X Joystick (PS3/PC) configs

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
These look awesome, thanks! Is there a reason there's no vid/pid on HID and SDL2?

**Comment by Jaffacakelover** [comment]
Simple reason, the 'Save autoconfig' option in Retroarch isn't saving any to the cfg file. Should there be? Will it have the same VID/PID across all drivers?

**Comment by hizzlekizzle** [comment]
heh, good reason :)

Yeah, they should be consistent across drivers, though the actual mapping / keycodes can vary. I think adding them would be good, if you don't mind.

**Comment by hizzlekizzle** [comment]
thanks!

**Pull request merged**
