### PR TITLE
Add support for the wired iNNEXT SNES remote

### PR DESCRIPTION
**Pull request by fekir**
It has the same input_vendor_id/input_product_id of

 * Hyperkin Sega Genesis Controller (6 buttons)
 * Retrolink Sega Saturn USB GamePad

Thus it introduces a new collision, but does not make the actual situation any worse.

### CODE REVIEW

**Comment by RobLoach** [comment]
Thank you much! Would you mind adding the labels?

```

input_b_btn_label = "Cross"
input_y_btn_label = "Square"
input_select_btn_label = "Share"
input_start_btn_label = "Options"
input_up_btn_label = "D-Pad Up"
input_down_btn_label = "D-Pad Down"
input_left_btn_label = "D-Pad Left"
input_right_btn_label = "D-Pad Right"
input_a_btn_label = "Circle"
input_x_btn_label = "Triangle"
input_l_btn_label = "L1"
input_r_btn_label = "R1"
input_l2_btn_label = "L2"
input_r2_btn_label = "R2"
input_l3_btn_label = "L3"
input_r3_btn_label = "R3"
input_l_x_plus_axis_label = "Left Analog X+"
input_l_x_minus_axis_label = "Left Analog X-"
input_l_y_plus_axis_label = "Left Analog Y+"
input_l_y_minus_axis_label = "Left Analog Y-"
input_r_x_plus_axis_label = "Right Analog X+"
input_r_x_minus_axis_label = "Right Analog X-"
input_r_y_plus_axis_label = "Right Analog Y+"
input_r_y_minus_axis_label = "Right Analog Y-"
input_menu_toggle_btn_label = "PS"
```

**Comment by fekir** [comment]
@RobLoach 

> Thank you much! Would you mind adding the labels?

All the labels with the description you provided?

It is a snes-like controller, not PS, thus it does not have cross, square, triangle and circle, but A,B,X,Y
Shouldn't the label reflect that?

It also has only one L and R, no L2,L3,R2,R3
Analog stick is also absent.
Do I need to add those labels even if the corresponding hardware does not exist?

What is `input_menu_toggle_btn_label`?

**Comment by RobLoach** [comment]
That was an example, apologies.

**Comment by fekir** [comment]
@RobLoach I've added the labels for the existing buttons.

**Pull request merged**
