### PR TITLE
Fix Android DS4 config select bindings and rename configs

### PR DESCRIPTION
**Pull request by andshrew**
Reference issue: https://github.com/libretro/retroarch-joypad-autoconfig/issues/642

The current configs for the DualShock 4 have the Touchpad configured as the select button, rather than the more conventional select button which would be the Share button.

This PR reconfigures the Share button to be the select button, and the Touchpad to be the RetroArch menu button (as far as I can tell the PlayStation button is unusable on Android as the system binds it as the Android home button).

Additionally this renames the configs for consistency; there should be two configs as there are two revisions of DS4.

This has been tested on an Nvidia Shield TV with v1 and v2 DS4s both connected by cable and bluetooth.

One inconsistency remains between the configs in that the v2 config has `input_r2` and `input_l2` bound to an axis instead of a button. Rebinding in application results in it defaulting to a button configuration, but as R2 and L2 seem to work fine in this axis configuration I've left this unchanged given that it seems to work fine.

### CODE REVIEW

**Comment by bslenul** [comment]
That's a weird one, maybe it varies between Android version or something? My phone is still under 7.0 and when I had my V1 Share button was "109".

Now I have a V2 and my bindings are completely different, this is what I have when rebinding:
```
input_device = "Wireless Controller"
input_vendor_id = "1356"
input_product_id = "2508"
input_b_btn = "97"
input_y_btn = "96"
input_select_btn = "104"
input_start_btn = "105"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "98"
input_x_btn = "99"
input_l_btn = "100"
input_r_btn = "101"
input_l2_btn = "102"
input_r2_btn = "103"
input_l3_btn = "109"
input_r3_btn = "108"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "+3"
input_r_y_minus_axis = "-3"
input_menu_toggle_btn = "110"
```
\+ touchpad being "106" (and yes, "110" is my PS button and it works fine for me when bound as "toggle menu").

**Comment by andshrew** [comment]
It's interesting that your controller is identified as `input_device = "Wireless Controller"` rather than `Sony Computer Entertainment Wireless Controller` which I guess suggests a different driver is being used.

It looks like Android 9 added native support for DS4 which could explain the difference you see.

I've also tested on an Android 7 phone now - albeit a Sony Xperia (so it had official support for DS4) - and while that also reports as just `Wireless Controller` the actual bindings match this config although in this case neither the touchpad or home button work.

It seems like Android may just too many variations to fit the potential bindings for the DS4 into the current RetroArch controller map selection system. It could possibly do with some additional selection criteria based on OS version.

I'd be inclined to suggest that bindings based on the official DS4 implementation from Android 9 should be used for the default auto config.

**Comment by bslenul** [comment]
Funny (and annoying...) how it can vary from a device to another :p 

> I'd be inclined to suggest that bindings based on the official DS4 implementation from Android 9 should be used for the default auto config.

Yeah, that would make sense IMO 👍

**Comment by offalynne** [comment]
Looks like it's mapped differently on Android 9 forward.

**Comment by RobLoach** [comment]
Merging this one. Let me know if there are any other updates needed.

**Pull request merged**
