### PR TITLE
(SDL2) Add ClockworkPi DevTerm

### PR DESCRIPTION
**Pull request by xordspar0**
Please be patient with me as I'm just figuring this out.

1. I only provided config for sdl2 because I have only figured out how to configure this device with sdl2 so far.
2. Is there a way to enable analog to digital conversion by default? This controller has a d-pad that's wired up as a pair of analog axes.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
you should be able to just assign them to retropad-up/down/left/right instead of the retropad analogs, regardless of whether the pad sees them as analog or digital.

**Comment by xordspar0** [comment]
I tried that by doing this:

```diff
- input_l_y_minus_axis = "-1"
- input_l_y_plus_axis = "+1"
- input_l_x_minus_axis = "-0"
- input_l_x_plus_axis = "+0"
+ input_up_btn = "-1"
+ input_down_btn = "+1"
+ input_left_btn = "-0"
+ input_right_btn = "+0"
```

But that didn't work. That made my d-pad do nothing. Retroarch doesn't seem to recognize axes as an option for mapping to buttons.

**Comment by hizzlekizzle** [comment]
It would be input_*_axis rather than input_*_btn in this case.

**Comment by xordspar0** [comment]
Ah, that works perfectly, thanks!

**Pull request merged**
