### PR TITLE
Create iBuffalo Classic USB Gamepad.cfg

### PR DESCRIPTION
**Pull request by Charco79**

### CODE REVIEW

**Comment by fr500** [comment]
well... no, you had to add the actual data in the file, you're just sending an empty file :)
live and learn

**Comment by Charco79** [comment]
Yeah I dunno so.

**Comment by fr500** [comment]
I'll add this for you this time

**Comment by Charco79** [comment]
Cheers, I doubt I will be a prolific contributor! lol

**Pull request closed without merging**
