### PR TITLE
Added Mad Catz 360, fixed Hori joystick config file.

### PR DESCRIPTION
**Pull request by theDripp**
- Edited/fixed the *Hori Real Arcade Pro 3 SA* autoconfig file to its proper button configuration.
horiarcadestick
- Added the *Mad Catz Xbox 360* controller autoconfig file.
madcatzxbox360

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Looks good, thanks! While we have you, would you mind adding the button labels, as well? It makes it easier for people to re-map them. Here's what that looks like:
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Sony-PlayStation3-DualShock3-Controller-USB.cfg

**Comment by theDripp** [comment]
Sure thing. In hind sight I should of checked and saw the other contributed config files to use as templates.

**Comment by theDripp** [comment]
All done! I ended up changing the buttons back on the HORI, as I realized I was mistaken. Added button labels for the Mad Catz controller and I added spaces in both configuration files for readability.

**Comment by hizzlekizzle** [comment]
Awesome. Thanks!

**Pull request merged**
