### PR TITLE
Update Arcade Joystick v1.1.cfg

### PR DESCRIPTION
**Pull request by lfanog**
Added "display name" / Changed "vendor id" and "product id"

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
What's up with the different vid/pid? is the other one incorrect?

**Comment by lfanog** [comment]
> 
> 
> What's up with the different vid/pid? is the other one incorrect?

I didn't observe it before. I checked now on USBDeview.

**Comment by lfanog** [comment]
Arcade Joystick v1 1

**Comment by hizzlekizzle** [comment]
I believe the old one is correct and the new one is the hex value. That is, 8282 is hex for 33410.

**Comment by lfanog** [comment]
> 
> 
> I believe the old one is correct and the new one is the hex value. That is, 8282 is hex for 33410.

Yes, you are correct.

:)

**Comment by twinaphex** [comment]
@hizzlekizzle So what do we do with this PR?

**Comment by lfanog** [comment]
I will close.

**Pull request closed without merging**
