### PR TITLE
Add udev config files

### PR DESCRIPTION
**Pull request by orbea**
Adds a config file for my gamestop brand usb xbox360 controller.

### CODE REVIEW

**Comment by orbea** [comment]
I added a commit for my Smartjoy snes to usb converter.

**Comment by hizzlekizzle** [comment]
Those look good! Would you mind adding the button labels, as well? This is a good example of how that looks:
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/android/Amazon%20Fire%20Game%20Controller.cfg

**Comment by orbea** [comment]
Sure, I added two more and will add button labels now.

**Comment by orbea** [comment]
I added the button labels as well as removed some unused buttons found on some of the controllers. The only thing that may be missing is the home buttons on some controllers which are not added when the autoconfig is generated? And also the turbo button on the Hori fightstick which does not seem to work at all...

**Comment by hizzlekizzle** [comment]
Good work! Thanks for these :)

**Pull request merged**
