### PR TITLE
redefinition of event codes for kernel > 4.15

### PR DESCRIPTION
**Pull request by tjustino**
Maybe the same fix that https://github.com/libretro/retroarch-joypad-autoconfig/pull/403

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Thanks for submitting! We may hold onto this for a bit until the newer kernel filters down to more distros.

**Comment by twinaphex** [comment]
Man, how many times are these guys going to screw around with the button bindings like this?

They already broke things badly one time before, now again.

**Comment by orbea** [comment]
This is a duplicate of https://github.com/libretro/retroarch-joypad-autoconfig/pull/403.

**Comment by hizzlekizzle** [comment]
Ok, we'll probably want to update this pretty soon. I think once Ubuntu puts out 18.04 (an LTS release), it'll be using 4.15 kernel.

**Comment by orbea** [comment]
Sounds reasonable. :)

**Comment by hizzlekizzle** [comment]
Ok, I merged the other almost-identical PR, so I'm going to close this one. Thanks for submitting, tjustino!

**Pull request closed without merging**
