### PR TITLE
Add configs for Spartan Gear Oplon

### PR DESCRIPTION
**Pull request by ltrvs**
A wired Shanwan based PS3/PC clone, identifies in various ways... Please reject this PR if unsure, I'm happy to use these as local configs in that case.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
It looks like the first one is okay, but the second one conflicts. Would you mind removing the second one from the PR and I can merge in the first?

**Comment by ltrvs** [comment]
Sure, but could you please first educate me how it conflicts? I noticed it had same PID and VID as the existing Betop config, but thought it wont conflict due to the different input_device value. Or is conflicting in some another way? Thanks!

**Comment by hizzlekizzle** [comment]
As far as I can tell, even though the input_device field is part of the calculation, if the vid and pid match, it's pretty much gonna get it. We just had to deactivate a whole bunch of profiles for this very reason.

**Comment by offalynne** [comment]
I believe those were configs that lacked a differentiation via VID, PID *or* input_device. RA scores configs on all 3. If the map is identical anyway seems kind of redundant though (haven’t checked if that’s the case here). @MatiasFernandez ?

**Comment by ltrvs** [comment]
Thanks for your comments. Maybe I'll wait until you agree about the possible conflict before deleting the config with Betops' VID:PID from this PR.

> If the map is identical anyway seems kind of redundant though (haven’t checked if that’s the case here).

The mapping is not the same for both of these controllers:

```
$ diff -Naur BETOP_AX1_BFM.cfg Spartan\ Gear\ Oplon.cfg  | grep input_ | grep -v label
 input_driver = "udev"
-input_device = "BETOP AX1 BFM"
-input_device_display_name = "BETOP AX1 BFM"
+input_device = "ShanWan PS3/PC Wired GamePad"
+input_device_display_name = "Spartan Gear Oplon"
 input_vendor_id = "8380"
 input_product_id = "21760"
-input_b_btn = "9"
-input_y_btn = "12"
-input_select_btn = "19"
-input_start_btn = "20"
+input_b_btn = "0"
+input_y_btn = "3"
+input_select_btn = "10"
+input_start_btn = "11"
 input_up_btn = "h0up"
 input_down_btn = "h0down"
 input_left_btn = "h0left"
 input_right_btn = "h0right"
-input_a_btn = "10"
-input_x_btn = "13"
-input_l_btn = "15"
-input_r_btn = "16"
-input_l2_btn = "17"
-input_r2_btn = "18"
-input_l3_btn = "22"
-input_r3_btn = "23"
+input_a_btn = "1"
+input_x_btn = "4"
+input_l_btn = "6"
+input_r_btn = "7"
+input_l2_btn = "8"
+input_r2_btn = "9"
+input_l3_btn = "13"
+input_r3_btn = "14"
 input_l_x_plus_axis = "+0"
 input_l_x_minus_axis = "-0"
 input_l_y_plus_axis = "+1"
 input_r_y_plus_axis = "+3"
 input_r_y_minus_axis = "-3"
```

**Comment by hizzlekizzle** [comment]
I'm okay with merging this and then we can always disable the conflicting one later if necessary.

**Pull request merged**
