### PR TITLE
add udev HORI RAP.V (Nintendo Switch)

### PR DESCRIPTION
**Pull request by whatdoineed2do**
https://hori.co.uk/real-arcade-pro-v-hayabusa-for-nintendo-switch

### CODE REVIEW

**Comment by offalynne** [comment]
can you add button labels?

**Comment by whatdoineed2do** [comment]
> can you add button labels?

@offalynne - all done and (re)verified

**Review by RobLoach — APPROVED** [review]
Looks good! Thanks a lot.

**Review by RobLoach — APPROVED** [review]
Looks good! Thanks a lot.

**Review by RobLoach — APPROVED** [review]

**Pull request merged**
