### PR TITLE
Renamed 347 .cfg file names: Replaced white space with underscore

### PR DESCRIPTION
**Pull request by davidhedlund**

### CODE REVIEW

**Comment by offalynne** [comment]
@RobLoach seems the garbage submissions are still out of control. I will unsubscribe from notifications for my own sanity but kindly suggest action taken to prevent further mangling of the repo's commit log by this user's content free zero-value pupl requests

**Comment by davidhedlund** [comment]
> @RobLoach seems the garbage submissions are still out of control. I will unsubscribe from notifications for my own sanity but kindly suggest action taken to prevent further mangling of the repo's commit log by this user's content free zero-value pull requests

I apologize if I caused problems. I'm trying to standardize the filenames, and I haven't used git in years.

**Comment by davidhedlund** [comment]
> content free zero-value pull requests

Are not the file name changed? Have I missed something?

**Comment by RobLoach** [comment]
> @RobLoach seems the garbage submissions are still out of control. I will unsubscribe from notifications for my own sanity but kindly suggest action taken to prevent further mangling of the repo's commit log by this user's content free zero-value pull requests

No issue on un-watching for your sanity. The libretro team has many members to help keep things rolling. Mental health is important, and you are able to check in whenever you have the capability to do so. Thanks so much for helping out 👍

**Comment by hizzlekizzle** [comment]
>Aren't the file names changed in my pull request? Have I missed something?

Yes, they're changed. No worries.

**Comment by offalynne** [comment]
I don't know if the conversation motivating this happened elsewhere but some opinions on why this should not be merged:

1. Profile names match device names per fields both in the file contents and the HID descriptors. These changes break that

2. In cases where a company rebrands by changing their spelling, this should not retroactively be applied to devices that still use the old branding on the physical device, packaging, descriptors, etc. as is the case of 8BitDo here

3. The commit log is already a disaster as a result of untested garbage PRs from this contributor, further merges of untested contributions leaves significant work for others to deal with later

**Comment by hizzlekizzle** [comment]
I'm not aware of any other conversations about this either for or against. We usually try to be forgiving with people who are still learning how to contribute (though not to the extent that we want an avoidably messy commit log), but 1 and 2 seem like pretty big problems in any case.

**Comment by davidhedlund** [comment]
[_If other contributors have made some changes in the past such as the filename in the example you provided, that is not a good reason to change 300+ files on a mistaken assumption, especially when you have not tested the outcome of your changes._](https://github.com/libretro/retroarch-joypad-autoconfig/issues/1063#issuecomment-1849092477)

**Comment by davidhedlund** [comment]
And it's not possible to submit a vice versa PR that replaces underscores with white spaces in all .cfg file names?

**Comment by RobLoach** [comment]
The goal is to have the `input_device` match the filename. The `input_device` is what the input driver discovers as the named ID of the controller. It also saves the device as `[input_device].cfg`, so we should keep them the same

**Comment by davidhedlund** [comment]
> The goal is to have the `input_device` match the filename.

I've noticed that this is far away from standardized, since people are renaming either the filename or the input_device variable. A simple bash script for GNU/Linux could be used to automate this by setting the file name as input_device variable value. What do you think about it? I can code it for you if you are interested.

> The `input_device` is what the input driver discovers as the named ID of the controller. It also saves the device as `[input_device].cfg`, so we should keep them the same

**Comment by offalynne** [comment]
> What do you think about it? I can code it for you if you are interested.

No.

The best choice is for the filename to be left alone so that it matches RetroArch's output to avoid contributors creating duplicates, however if past contributions have changed the file name **_these should be left alone_** as "cleaning up" is not a valid reason to create a pull request that is likely to raise further issues while solving none.

In general please do not create pull requests that touch mappings for devices you _**do not own**_ as you lack the capability to _**test your changes**_ and confirm you have not in fact degraded the performance of RetroArch Autoconfig.

**Comment by davidhedlund** [comment]
> > What do you think about it? I can code it for you if you are interested.
> 
> No.
> 
> The best choice is for the filename to be left alone so that it matches RetroArch's output to avoid contributors creating duplicates, however if past contributions have changed the file name **_these should be left alone_** as "cleaning up" is not a valid reason to create a pull request that is likely to raise further issues while solving none.
> 
> In general _**please do not create pull requests that touch mappings for devices you do not own**_ as you will lack the capability to properly _**test your changes**_ and confirm you have not in fact degraded the functionality RetroArch Autoconfig.

It was just an offer, thank you for being clear. Is this worth documentation @hizzlekizzle ?

**Comment by davidhedlund** [comment]
> And it's not possible to submit a vice versa PR that replaces underscores with white spaces in all .cfg file names?

@offalynne What is your opinion?

**Comment by hizzlekizzle** [comment]
>Is this worth documentation

Yes, I'd say the README could use some clarification on these topics, and "please don't touch files you can't personally test" seems like a good addition.

**Comment by davidhedlund** [comment]
> The goal is to have the `input_device` match the filename. The `input_device` is what the input driver discovers as the named ID of the controller. It also saves the device as `[input_device].cfg`, so we should keep them the same

I just created a [PR](https://github.com/libretro/retroarch-joypad-autoconfig/pull/1068/files): $lsusb says: "Sony Corp. DualSense Wireless Controller" -- so should I rename the file to "Sony Corp. DualSense Wireless Controller.cfg". Personally, I strongly prefer just Sony_DualSense.cfg since it's short and concise.

**Comment by davidhedlund** [comment]
I proposed PRs with "Sony ", and "Nintendo " in the beginning of filenames for controllers made by these companies. I need it to organize, so I can proceed with more detailed working plans. Furthermore, I own both a Sony DualSense (PS5), and a Nintendo Switch Pro Controller, and I've contributed to these controllers.

**Comment by davidhedlund** [comment]
> I proposed PRs with "Sony ", and "Nintendo " in the beginning of filenames for controllers made by these companies. I need it to organize, so I can proceed with more detailed working plans. Furthermore, I own both a Sony DualSense (PS5), and a Nintendo Switch Pro Controller, and I've contributed to these controllers.
> 
> I could not sync our repo with my fork since I have pushed two commits that must be managed first. As a consequence and since I'm not exeprienced with git, I had to submit multiple PRs by using the web interface.

To describe the background to my PR drafts: Today I learned that the device name may not include the name of the company for practical reasons.

Example for DualSense:
* In GNU/Linux, $lsusb: `Sony Corp. DualSense Wireless Controller`
* In Android, the Bluetooth device name is: `DualSense Wireless Controller`

Example for Nintendo Switch Pro Controller:
* In GNU/Linux, $lsusb: `Nintendo Co., Ltd Switch Pro Controller`
* In Android, the Bluetooth device name is: `Pro Controller`

So to group the files alphabetically, they must start with the company name.

**Pull request closed without merging**
