### PR TITLE
fix up this encoder across platforms

### PR DESCRIPTION
**Pull request by grant2258**
please see https://github.com/libretro/retroarch-joypad-autoconfig/issues/454 for details

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
I guess this will interfere with some of the Dragonrise gamepads?

**Comment by grant2258** [comment]
no they are a diff  number and its numbered the same as the dual shock one anyway the only conflict is the retro n64 posted on another issue here

**Comment by grant2258** [comment]
if there is any issue or conficts some how ill add the second analogue stick in :). I can see there being any though

**Comment by dankcushions** [comment]
why did you remove the instructions for how to set up this stick re: R1/R2 third column layout? https://github.com/libretro/retroarch-joypad-autoconfig/pull/455/files#diff-2fcd714f4f167d953135c36721912e30

that was good information. reinstate it.

**Pull request merged**
