### PR TITLE
Updated Retro-Bit Tribute64 - USB (D-Input).cfg

### PR DESCRIPTION
**Pull request by andrewkendall**
Updated input_vendor_id and input_product_id for Retro-Bit Tribute64 - USB (D-Input)

I've now taken the vid/pid from Windows device manager rather than the auto-generated RetroArch values.

Tested and fully working in Mupen64Plus-Next, hopefully, these are the correct and unique device values.

### CODE REVIEW

**Comment by twinaphex** [comment]
Hmm, seems there is a merge conflict here that has to be resolved first.

**Comment by hizzlekizzle** [comment]
Those are the same values, just in hex format, unfortunately.

**Comment by andrewkendall** [comment]
Sorry about that! It looks like those must be the only values in D-Input mode so I'll close this. I'll look at the other mode and see if values are unique to the device for that one. Thank you for spotting the values were the same, just in hex. It's a shame as this is the default mode every time it's plugged in, but hopefully, the config still comes in useful to someone.

**Comment by hizzlekizzle** [comment]
No problem! We appreciate the submission(s) all the same :)

**Pull request closed without merging**
