### PR TITLE
Create USBgamepad.cfg

### PR DESCRIPTION
**Pull request by HerbFargus**
Configs for a cheap SNES USB controller

### CODE REVIEW

**Comment by twinaphex** [comment]
Can you provide VID and PID values for this too? This is to prevent false positives since the input device name is fairly generic.

**Comment by HerbFargus** [comment]
Updated

**Comment by twinaphex** [comment]
Can you change those values to decimal?

**Comment by Alcaro** [comment]
What is o81f in decimal?

**Comment by twinaphex** [comment]
Still doesn't have decimal values for VID/PID, but whatever I guess.

**Comment by HerbFargus** [comment]
just changed it using https://www.branah.com/ascii-converter and got decimal values- is that what you are looking for? I just committed the changes, right after you merged it, should I submit another pull request?

**Comment by twinaphex** [comment]
Yes, submit another PR.

**Comment by HerbFargus** [comment]
done

**Pull request merged**
