### PR TITLE
Add udev Nintendo Switch Online Mega Drive/Genesis 3btn Controller

### PR DESCRIPTION
**Pull request by nfp0**
This adds mapping on the udev driver for the Nintendo Switch Online Mega Drive/Genesis 3btn Controller.

I also tried to create a mapping for dinput for Windows, but it seems this controller shares the same input_vendor_id and input_product_id than the Nintendo Switch Online SNES controller, and I ran into the issue I described here: https://github.com/libretro/retroarch-joypad-autoconfig/issues/760#issuecomment-1016447314

It would be nice to also have dinput support, as this being a wireless official replica of the Mega Drive/Genesis controller is certainly going to be a very popular controller as soon as stock arrives.

### CODE REVIEW

**Comment by offalynne** [comment]
Comment out vendor and product on both configs (SNES and Gen) and let them match on device name instead.

**Comment by nfp0** [comment]
> Comment out vendor and product on both configs (SNES and Gen) and let them match on device name instead.

As soon as I did that to the SNES file, it stopped being recognized.
If I name it `input_device = "Wireless Gamepad"` it gets detected though, but this is useless as it seems all Bluetooth controllers have this name on Windows.

**Comment by offalynne** [comment]
Yeah, not ideal ! See https://github.com/libretro/retroarch-joypad-autoconfig/issues/760#issuecomment-1016632007

I wonder if for now it might be appropriate to make a superset of both mappings and include both names eg. `input_select_btn_label = "Select/MODE"` not ideal but perhaps an acceptable stopgap.

**Comment by nfp0** [comment]
I don't believe that would be possible, because the button mappings don't coincide between the 2 controllers.
Of course, it is also not desirable that in the current state, completely different controllers get mapped to the same autoconfig file and only one of them will operate correctly.
I'll open an issue on the main project and try and see why the device name is not being read on dinput.

Regardless, udev detects both controllers nicely on Linux, so I opened this merge request for it.

**Comment by offalynne** [comment]
If you're able & willing would love to have SDL mappings as well: https://github.com/gabomdq/SDL_GameControllerDB

**Comment by nfp0** [comment]
@offalynne I tried mapping on the SDL2 controller driver on the Retroarch Input menu, but some buttons don't register at all, so I gave up.
Am I doing something wrong?

**Comment by offalynne** [comment]
@nfp0 yeah sorry I meant for the SDL db's benefit in the repo I linked, completely unrelated to RetroArch

**Comment by RobLoach** [comment]
There's a conflict with `udev/SNES Controller.cfg`
```
input_driver = "udev"
input_device_display_name = "Nintendo Switch SNES Controller"
input_device = "SNES Controller"
input_vendor_id = "1406"
input_product_id = "8215"
input_b_btn = "0"
input_y_btn = "2"
input_select_btn = "8"
input_start_btn = "9"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "1"
input_x_btn = "3"
input_l_btn = "4"
input_r_btn = "5"
input_l2_btn = "6"
input_r2_btn = "15"
input_l2_btn_label = "LZ"
input_r2_btn_label = "RZ"
```

**Comment by offalynne** [comment]
> Comment out vendor and product on both configs (SNES and Gen) and let them match on device name instead.

**Comment by nfp0** [comment]
@RobLoach Yeah, I've tested with the SNES controller as well and it seems to be detected correctly even with my MegaDrive/Genesis file.
What should be done in these situations? Should the input_vendor_id and input_product_id be omitted?

@offalynne 
Oh ok, I might get to it later.

**Comment by nfp0** [comment]
Done. Commented out the ids. Tested and both controllers are detected correctly.
Took the chance and also added labels to the SNES controller.

**Comment by RobLoach** [comment]
Thanks a lot, both!

**Comment by nfp0** [comment]
> If you're able & willing would love to have SDL mappings as well: https://github.com/gabomdq/SDL_GameControllerDB

@offalynne Done! Opened an issue here: https://github.com/gabomdq/SDL_GameControllerDB/issues/546

**Comment by offalynne** [comment]
@nfp0 could you reach me by email if possible ? i could use some help regarding adding to open source knowledge/compatibility for these devices (not having access to these specific devices myself) and email would be most convenient. you can reach me on alviscera at gmail. regardless, thanks again !

**Comment by nfp0** [comment]
@offalynne Sure. Sent you an email.

**Pull request merged**
