### PR TITLE
Create android/Pro Controller.cfg

### PR DESCRIPTION
**Pull request by davidhedlund**
```
# Nintendo Switch Pro Controller (with nintendo-hid)
# 
# This is the first fully working Android autoconfig
# for Nintendo Switch Pro Controller as far as I know
# It requires Android 12.
# 
# Disclaimer:
# The Nintendo Switch Pro Controller has other binding
# for earliers Android versions. However, the Bluetooth
# connectivity issue in Android 11 and earlier makes the
# controller useless for gaming.
# 
# Evaluated by David Hedlund.
```

Generated from
* OS: Google TV 12 (it's based on Android 12, se below)
* RA installed via: Google Play
* Retroarch version: 1.9.12

RetroArch:
* Main Menu -> Information -> System Information -> Frontend Identifier: android [default]
* Main Menu -> Information -> System Information -> Frontend Name: Chromecast HD
* Main Menu -> Information -> System Information -> Frontend OS: Android (v12.0)
* Settings -> Drivers -> Controller -> Controller: android [default]

# IDs
The file is a modified copy from udev/Create Nintendo - Switch Pro Controller.cfg, including: 
```
# Hex vid/pid: 057e:2009
input_vendor_id = "1406"
input_product_id = "8201"
```

However, currently, when I'm connecting the Nintendo Switch Pro Controller, RA pops up a "**8BitDo SN30 Pro+ (Switch Mode) configured on port #1**" (android/8BitDo_SN30_Pro_for_Android.cfg), and sometimes "**Nintendo Switch Pro Controller configured on port #1**" (sdl2/Nintendo Switch Pro Controller.cfg). So I'm a bit confused which ID that should be used.

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
HI, what's the state of this? When is this PR ready for merge?

**Comment by davidhedlund** [comment]
> HI, what's the state of this? When is this PR ready for merge?

It's ready.

**Comment by hizzlekizzle** [comment]
seems fine to me

**Comment by davidhedlund** [comment]
> seems fine to me

From https://github.com/libretro/retroarch-joypad-autoconfig/pull/1066/checks

image

```
Some duplicate profiles were found
Duplicates inside 'android'
Vendor ID: 1406 - Product ID: 8201 - Name: Pro Controller
- android/8BitDo SN30 Pro+ (Switch Mode).cfg
- android/Pro Controller.cfg
```

How do we solve that?

**Comment by RobLoach** [comment]
Duplicate vendor/product id pairs cause conflicts with RA. While it still "works", it can confuse the controller types. I'd honestly recommend just deleting `android/8BitDo SN30 Pro (Switch Mode).cfg` with this as its replacement.

People can use the 8BitDo controller in a different mode just fine.

**Review by RobLoach — CHANGES_REQUESTED** [review]
Delete android/8BitDo SN30 Pro (Switch Mode).cfg .

**Comment by davidhedlund** [comment]
> Delete android/8BitDo SN30 Pro (Switch Mode).cfg .

We also have a file called `[8BitDo SN30 Pro+ (Switch Mode).cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/android/8BitDo%20SN30%20Pro%2B%20(Switch%20Mode).cfg)`. What should we do with it?

**Comment by davidhedlund** [comment]
> Duplicate vendor/product id pairs cause conflicts with RA. While it still "works", it can confuse the controller types. I'd honestly recommend just deleting `android/8BitDo SN30 Pro (Switch Mode).cfg` with this as its replacement.
> 
> People can use the 8BitDo controller in a different mode just fine.

Just to be clear since we have so many autoconfig files, you mean [android/8BitDo SN30 Pro+ (Switch Mode).cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/android/8BitDo%20SN30%20Pro%2B%20(Switch%20Mode).cfg) (notice the "+").

**Comment by davidhedlund** [comment]
> Delete android/8BitDo SN30 Pro (Switch Mode).cfg .

* Here you go: https://github.com/libretro/retroarch-joypad-autoconfig/pull/1106

**Comment by davidhedlund** [comment]
Why did you close this and those?:
* https://github.com/libretro/retroarch-joypad-autoconfig/pull/1106#event-11606087850
* https://github.com/libretro/retroarch-joypad-autoconfig/pull/1067#event-11606091358
* https://github.com/libretro/retroarch-joypad-autoconfig/pull/1088#event-11606091414

**Pull request closed without merging**
