### PR TITLE
Update and rename FC30_Gamepad.cfg to 8Bitdo FC30 GamePad.cfg

### PR DESCRIPTION
**Pull request by CaptainAlphabet**
- Renamed file to match the other 8Bitdo autoconfig file names
- Added VID/PID
- Added display name
- Fixed SELECT button code

### CODE REVIEW

**Comment by fr500** [comment]
Please add descriptors to your contributions, I didn't catch that before but it's the correct way to contribute, you can check and example here:

https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/android/8Bitdo%20NES30%20GamePad%20Joystick.cfg

**Comment by CaptainAlphabet** [comment]
What do you mean? I always add descriptors/labels to autoconfig files.

https://github.com/CaptainAlphabet/retroarch-joypad-autoconfig/blob/patch-2/android/8Bitdo%20FC30%20GamePad.cfg

Or do you talk about the comment at the beginning of your mentioned file?

**Comment by CaptainAlphabet** [comment]
Any feedback on this?

**Comment by CaptainAlphabet** [comment]
Thank you :-)

**Pull request merged**
