### PR TITLE
Suggestion: Use R3 as menu button on DualShock controllers

### PR DESCRIPTION
**Pull request by CaptainAlphabet**
Added display names to DualShock controllers, too.

### CODE REVIEW

**Comment by CaptainAlphabet** [comment]
Please just close or comment this pull request if undesired.

**Comment by twinaphex** [comment]
@fr500 or @kivutar should take a look at this I guess.

**Comment by Kivutar** [comment]
We already have the L3+R3 combination for that.

I'm not for binding a button to menu_toggle, because some games may use this button.

**Comment by CaptainAlphabet** [comment]
All right. Thanks for your feedback. Then I'm going to close this one.

**Pull request closed without merging**
