### PR TITLE
Create config for EasySMX  SM-9110

### PR DESCRIPTION
**Pull request by shennguyenrs**
Hi,
My controller is EasySMX SM-9110 and it is not autodetected on Lakka.tv. So I have generated a file for it. I found that there is a file for EasySMX controller, however, it has a different in vendor id and product id so maybe that's why it is not working. Thank you.

image

### CODE REVIEW

**Comment by offalynne** [comment]
can you provide labels?

**Comment by shennguyenrs** [comment]
> can you provide labels?

Sorry, I don't understand what you mean? Is it EasySMX?

**Comment by shennguyenrs** [comment]
> can you provide labels?

I have updated the device_display_name. Is it label that you mentioned?

**Comment by bslenul** [comment]
You should add the value for the Home button as `input_menu_toggle_btn` too so it can act as "Toggle Menu" by default.

Add this at the end of the file (replace "XXX" with Home button value on the first line, of course :p) + labels (the button names) and it should be fine:
```
input_menu_toggle_btn = "XXX"

input_b_btn_label = "A"
input_y_btn_label = "X"
input_select_btn_label = "Select"
input_start_btn_label = "Start"
input_up_btn_label = "D-Pad Up"
input_down_btn_label = "D-Pad Down"
input_left_btn_label = "D-Pad Left"
input_right_btn_label = "D-Pad Right"
input_a_btn_label = "B"
input_x_btn_label = "Y"
input_l_btn_label = "Left Bumper"
input_r_btn_label = "Right Bumper"
input_l2_axis_label = "Left Trigger"
input_r2_axis_label = "Right Trigger"
input_l3_btn_label = "Left Thumb"
input_r3_btn_label = "Right Thumb"
input_l_x_plus_axis_label = "Left Analog X+"
input_l_x_minus_axis_label = "Left Analog X-"
input_l_y_plus_axis_label = "Left Analog Y+"
input_l_y_minus_axis_label = "Left Analog Y-"
input_r_x_plus_axis_label = "Right Analog X+"
input_r_x_minus_axis_label = "Right Analog X-"
input_r_y_plus_axis_label = "Right Analog Y+"
input_r_y_minus_axis_label = "Right Analog Y-"
input_menu_toggle_btn_label = "Home"
```

**Comment by shennguyenrs** [comment]
I have updated labels and tested the config file again 👍

**Review by RobLoach — APPROVED** [review]
Thanks!

**Pull request merged**
