### PR TITLE
Android: iPega PG-9023 config

### PR DESCRIPTION
**Pull request by kylon**

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Hey, looks good! While we have you here, would you mind adding the button labels, as well? Here's an example:
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/android/8Bitdo_Pro_FC30_BT.cfg

**Comment by kylon** [comment]
yea, give me a few minutes

**Comment by kylon** [comment]
here you go

**Comment by hizzlekizzle** [comment]
Beautiful! Thanks :)

**Pull request merged**
