### PR TITLE
Create Sanmos JY-P62U Series ONLINE GRIP.cfg

### PR DESCRIPTION
**Pull request by ya-ma-ka-wa**

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
While you're here, can I trouble you to add the button labels, as well?

**Comment by ya-ma-ka-wa** [comment]
Please confirm it is.

**Comment by ya-ma-ka-wa** [comment]
IMG_0070 - コピー
This is an image.

**Comment by hizzlekizzle** [comment]
This looks great, thanks!

**Pull request merged**
