### PR TITLE
[Ready for RetroArch 1.19.2] udev: Remove `Sony-PlayStation4-DualShock4-Controller.cfg` -- Merge DualShock v1 and v2 in #1168

### PR DESCRIPTION
**Pull request by davidhedlund**
* Delete the file in this PR to merge https://github.com/libretro/retroarch-joypad-autoconfig/pull/1168
* Merge DualShock 4 v1 and v2: https://github.com/libretro/RetroArch/pull/16990

### CODE REVIEW

**Review by RobLoach — CHANGES_REQUESTED** [review]
Could likely merge this PR with the others relating to PlayStation4

**Comment by cmitu** [comment]
IMHO this PR - and the other similar ones that delete profiles - shouldn't be merged until at least one RetroArch release is made. Right now there's no release including https://github.com/libretro/RetroArch/pull/16990, the change which makes this PR possible.
Also, if users don't have the last RetroArch version and update their controller profiles can potentially lose the profile they used, since their RetroArch version doesn't implement the profile matching from https://github.com/libretro/RetroArch/pull/16990.

**Comment by davidhedlund** [comment]
> IMHO this PR - and the other similar ones that delete profiles - shouldn't be merged until at least one RetroArch release is made. Right now there's no release including [libretro/RetroArch#16990](https://github.com/libretro/RetroArch/pull/16990), the change which makes this PR possible. Also, if users don't have the last RetroArch version and update their controller profiles can potentially lose the profile they use, since their RetroArch version doesn't implement the profile matching from [libretro/RetroArch#16990](https://github.com/libretro/RetroArch/pull/16990).

I replaced "[READY]" with "[Ready for RetroArch 1.19.2]" in the titles for these PRs.

**Comment by davidhedlund** [comment]
> Could likely merge this PR with the others relating to PlayStation4

* Merged: https://github.com/libretro/retroarch-joypad-autoconfig/pull/1168/commits/f6da3b8069a855927ab6cbf214c7695bd81a2080

**Pull request closed without merging**
