### PR TITLE
Create 8Bitdo Saturn Controller Modkit autoconfig.

### PR DESCRIPTION
**Pull request by Happyarch**
This aims to add an autoconfig for the 8Bitdo Sega Saturn Controller Modkit.

### CODE REVIEW

**Comment by Happyarch** [comment]
Also I'm new to using git so I may have accidentally opened two pull requests. Sorry about that.

**Comment by offalynne** [comment]
Where's the mode button?

**Comment by Happyarch** [comment]
> Where's the mode button?

The Saturn natively doesn't have a mode button but the microcontroller simulates it by pressing up + start.

**Review by RobLoach — APPROVED** [review]
This seems appropriate. Thanks!

**Pull request merged**
