### PR TITLE
Rename SNES PC Game Pad    SNES PC Game Pad   .cfg to Nintendo SNES P…

### PR DESCRIPTION
**Pull request by davidhedlund**
…C Game Pad    SNES PC Game Pad   .cfg

Nintendo

### CODE REVIEW

**Comment by davidhedlund** [comment]
> @davidhedlund Would you mind combining all of these pull requests into one? You can work on your own branch, and then open a Pull Request with all the changes you're looking for in one.

Yesterday after my latest mass PR I started to read https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository

Please give me a few days.

Thak you Rob

**Comment by davidhedlund** [comment]
I clicked on "Ready for review" on all PRs, they now say "Required statuses must pass before merging"

**Comment by davidhedlund** [comment]
After my PRs have passed statuses, I'll create a new pull request and merge my branches to it as described here: https://youtu.be/5g37NElQnCQ?t=76

**Comment by davidhedlund** [comment]
> > @davidhedlund Would you mind combining all of these pull requests into one? You can work on your own branch, and then open a Pull Request with all the changes you're looking for in one.
> 
> Yesterday after my latest mass PR I started to read https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository
> 
> I clicked on "Ready for review" on all PRs, they now say "Required statuses must pass before merging"
> 
> After my PRs have passed statuses, I'll create a new pull request and merge my branches to it as described here: https://youtu.be/5g37NElQnCQ?t=76
> 
> [Self-reminder: Merge all branch-4 to branch-19]

Can you please re-read this?

**Comment by RobLoach** [comment]
> I clicked on "Ready for review" on all PRs, they now say "Required statuses must pass before merging"

Feel free to ignore the checked status. There are two...
1. GitHub Actions - Will check if there are duplicates via the Ruby script: https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/.verify_duplicate_profiles.rb
2. Travis - This is the old continuous integration server we used that is no longer in use since we're on github actions now

Given that, feel free to ignore the status checks :+1:

**Comment by davidhedlund** [comment]
> > I clicked on "Ready for review" on all PRs, they now say "Required statuses must pass before merging"
> 
> Feel free to ignore the checked status. There are two...
> 
>     1. GitHub Actions - Will check if there are duplicates via the Ruby script: https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/.verify_duplicate_profiles.rb
> 
>     2. Travis - This is the old continuous integration server we used that is no longer in use since we're on github actions now
> 
> 
> Given that, feel free to ignore the status checks 👍

I'm closing my pull requests. I made the script that I was talking about before, that will generate the .cfg files to eliminate human errors completely.

**Pull request closed without merging**
