### PR TITLE
Create Retro-Bit_Genesis_8_Button_Arcade_Pad

### PR DESCRIPTION
**Pull request by coolspot18**
I noticed udev/Retrolink_Sega_Saturn_USB_GamePad also has the vendor and product id, not sure if this will cause any problems.

This is the new 8 button arcade pad from Retro-bit, officially licensed from Sega.

### CODE REVIEW

**Comment by offalynne** [comment]
Unfortunately they do conflict, so this should probably be committed but commented out as per @MatiasFernandez’s recent edits until the project is able to identify the difference. Could you share a lusb dump here for posterity?

**Comment by offalynne** [comment]
Unfortunately they do conflict, so this should probably be committed but commented out as per @MatiasFernandez’s recent edits until the project is able to identify the difference. Could you share a lsusb dump here for posterity?

**Comment by MatiasFernandez** [comment]
@offalynne how did you find it's conflicting? I don't see a conflict 🤔

**Comment by coolspot18** [comment]
@MatiasFernandez  This configuration for a Retrolink Sega Saturn USB Gamepad has the same vendor ID but it's under the UDEV folder: 

https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Retrolink_Sega_Saturn_USB_GamePad.cfg

vendor_id: 121
product_id: 17

I normally used Windows, but I plugged it into my Linux box and it shows up as a DragonRise Gamepad:
```
Bus 001 Device 005: ID 0079:0011 DragonRise Inc. Gamepad
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0        64
  idVendor           0x0079 DragonRise Inc.
  idProduct          0x0011 Gamepad
  bcdDevice            1.05
  iManufacturer           1 SWITCH CO.,LTD.
  iProduct                2 USB Gamepad
  iSerial                 3 AZ-RB-SGA-215 B0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           34
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     101
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              10
Device Status:     0x0000
  (Bus Powered)
```

**Comment by MatiasFernandez** [comment]
AFAIK you can use one driver at a time. So the only conflicts that are important are conflicts within the same folder (@hizzlekizzle correct me if I'm wrong). In addition to that, the "identifier" for the device is a combination of `input_device`, `input_vendor_id`, and `input_product_id`. So, to have a conflict you must have two files within the same folder having the same value for the three of them. 

Note: "empty" is considered a value, so two devices sharing vendor and product ids but without an input_device attribute are considered equal.

In this case, I think we don't have a conflict. But I would wait for additional confirmation.

**Comment by offalynne** [comment]
good catch @MatiasFernandez i failed to notice that this was in xinput and not udev, my mistake. the devices with udev configs @coolspot18 referred to *would* likely conflict (something i’ve tested with SDL2’s gamepad detection but haven’t confirmed under RA-AC), but since those are yet-unmapped for Windows in this repo this one can stay and sets the precedent for now 😄

@coolspot18 thanks for all the additional clarification you’ve done, since this is a Windows config could you provide the Windows terminal output from ‘ wmic path Win32_PnPEntity where "Name like 'HID-compliant%%'" ‘ pertaining to this device ? 😄

**Comment by coolspot18** [comment]
@offalynne Here is the wmic dump:

dinput:
```
Availability  Caption                                ClassGuid                               CompatibleID  ConfigManagerErrorCode  ConfigManagerUserConfig  CreationClassName  Description                            DeviceID                                             ErrorCleared  ErrorDescription  HardwareID                                                                                                                                                                                   InstallDate  LastErrorCode  Manufacturer               Name                                   PNPClass  PNPDeviceID                                          PowerManagementCapabilities  PowerManagementSupported  Present  Service  Status  StatusInfo  SystemCreationClassName  SystemName      
              HID-compliant game controller          {745a17a0-74d3-11d0-b6fe-00a0c90f57da}                0                       FALSE                    Win32_PnPEntity    HID-compliant game controller          HID\VID_0079&PID_0011\6&2671908B&0&0000                                              {"HID\VID_0079&PID_0011&REV_0105", "HID\VID_0079&PID_0011", "HID\VID_0079&UP:0001_U:0004", "HID_DEVICE_SYSTEM_GAME", "HID_DEVICE_UP:0001_U:0004", "HID_DEVICE"}                                                          (Standard system devices)  HID-compliant game controller          HIDClass  HID\VID_0079&PID_0011\6&2671908B&0&0000                                                                     TRUE              OK                  Win32_ComputerSystem     DESKTOP-GAMING  
```

Xinput (Start + B for 5 seconds will switch the mode temporary until the next time it is plugged in):

```
Availability  Caption                                ClassGuid                               CompatibleID  ConfigManagerErrorCode  ConfigManagerUserConfig  CreationClassName  Description                            DeviceID                                             ErrorCleared  ErrorDescription  HardwareID                                                                                                                                                                                   InstallDate  LastErrorCode  Manufacturer               Name                                   PNPClass  PNPDeviceID                                          PowerManagementCapabilities  PowerManagementSupported  Present  Service  Status  StatusInfo  SystemCreationClassName  SystemName      
              HID-compliant game controller          {745a17a0-74d3-11d0-b6fe-00a0c90f57da}                0                       FALSE                    Win32_PnPEntity    HID-compliant game controller          HID\VID_045E&PID_028E&IG_00\7&35800794&0&0000                                        {"HID\VID_045E&PID_028E&IG_00", "HID\VID_045E&UP:0001_U:0005", "HID_DEVICE_SYSTEM_GAME", "HID_DEVICE_UP:0001_U:0005", "HID_DEVICE"}                                                                                      (Standard system devices)  HID-compliant game controller          HIDClass  HID\VID_045E&PID_028E&IG_00\7&35800794&0&0000                                                               TRUE              OK                  Win32_ComputerSystem     DESKTOP-GAMING  
```

**Comment by offalynne** [comment]
thanks

> REV_0105

is the value that RA might do well to further differentiate these pads in the future as it’s unique between several devices that are otherwise currently indistinguishable. thanks for the extra effort 👍

**Comment by hizzlekizzle** [comment]
> So the only conflicts that are important are conflicts within the same folder

I believe this is the case, yes.

I really appreciate the attention on these PRs, btw, @offalynne and @MatiasFernandez !

**Pull request merged**
